export const notification = {
    FRIEND_REQUEST_RECEIVED: 'FRIEND_REQUEST_RECEIVED',
    FRIEND_REQUEST_ACCEPT: 'FRIEND_REQUEST_ACCEPT',
    BIRTHDAY_NOTIFICATION: 'BIRTHDAY_NOTIFICATION',
    INVALID_NOTIFICATION: 'INVALID_NOTIFICATION'
}