export const notification = {
    FRIEND_REQUEST_RECEIVED: 'FRIEND_REQUEST_RECEIVED',
    FRIEND_REQUEST_ACCEPT: 'FRIEND_REQUEST_ACCEPT',
    FRIEND_REQUEST_ACCEPT_SUCCESS_SENDER: 'You both are now friends',
    FRIEND_REQUEST_ACCEPT_SUCCESS_RECEIVER: 'accepted your friend request',
    BIRTHDAY_NOTIFICATION: 'BIRTHDAY_NOTIFICATION',
    TAG_NOTIFICATION: 'TAG_NOTIFICATION',
    INVALID_NOTIFICATION: 'INVALID_NOTIFICATION'
}